# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49aefdd881e60f3c1645faf9c5c202c4945e304c3fff52726003640f8190de44ee5df664262dbc409182f15ab8b6e763d6533ac71d51e1cc32e3320a5060516e

test:
  secret_key_base: 53db6c91d3e81efd56a04cb8648ddc9afe840acf42889d5a213c852f1bc3e56af30337f5713e77efa0b045e0f2783666f5325afb22d478a198756c95ef931af2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
